CooperativeAccounting/Controllers/LoanController.cs
using System;
using System.Linq;
using CooperativeAccounting.Models.DataBaseConnections;
using CooperativeAccounting.Models.Encryption;
using CooperativeAccounting.Models.Entities;
using CooperativeAccounting.Models.Enum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CooperativeAccounting.Controllers
{
    public class LoanController : Controller
    {
        private readonly CooperativeAccountingDataContext _databaseConnection;

        /// <summary>
        ///     Intitialize some connections from the class constructor
        /// </summary>
        /// <param name="databaseConnection"></param>
        public LoanController(CooperativeAccountingDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
        }
        [SessionExpireFilter]
        public IActionResult Index()
        {
            return View(_databaseConnection.Loans.Include(n => n.AppUser).Include(n => n.TransactionType).ToList());
        }
        [SessionExpireFilter]
        public IActionResult Create(string id)
        {
            ViewBag.AppUserId = new SelectList(_databaseConnection.AppUsers.Where(n => n.RoleId > 1).ToList(),
                "AppUserId",
                "Name");
            ViewBag.BankId = new SelectList(_databaseConnection.Banks.ToList(), "BankId",
                "Name");
            var loan = new Loan();
            if (id == "yes")
            {
                loan.Emergency = true;
            }
            return View(loan);
        }

        [HttpPost]
        [SessionExpireFilter]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Loan loan)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            loan.CreatedBy = signedInUserId;
            loan.LastModifiedBy = signedInUserId;
            loan.DateCreated = DateTime.Now;
            loan.DateLastModified = DateTime.Now;
            loan.TransactionTypeId = 2;

            var transaction = new Transaction
            {
                CreatedBy = signedInUserId,
                LastModifiedBy = signedInUserId,
                DateCreated = DateTime.Now,
                DateLastModified = DateTime.Now,
                Amount = loan.Amount,
                AppUserId = loan.AppUserId,
                TransactionDate = loan.TransactionDate,
                TransactionName = loan.Purpose,
                TransactionTypeId = 2
            };
            var accountType = _databaseConnection.TransactionTypes.Find(loan.TransactionTypeId);
            if (accountType.Debit || accountType.Loan)
            {
                transaction.Action = TransactionAction.Debit.ToString();
            }

            if (accountType.Credit)
            {
                transaction.Action = TransactionAction.Credit.ToString();
            }

            _databaseConnection.Transactions.Add(transaction);
            _databaseConnection.SaveChanges();

            loan.TransactionId = transaction.TransactionId;
            if (String.IsNullOrEmpty(loan.FirstGuarantorName))
            {
                loan.FirstGuarantorName = "Guarantor";
            }
            if (String.IsNullOrEmpty(loan.SecondGuarantorName))
            {
                loan.SecondGuarantorName = "Guarantor";
            }
            if (String.IsNullOrEmpty(loan.FirstGuarantorMobile))
            {
                loan.FirstGuarantorMobile = "00000000";
            }
            if (String.IsNullOrEmpty(loan.SecondGuarantorMobile))
            {
                loan.SecondGuarantorMobile = "00000000";
            }
            _databaseConnection.Loans.Add(loan);
            _databaseConnection.SaveChanges();

            TempData["display"] = "You have successfully applied for a new loan!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public IActionResult Edit(long id)
        {
            var loan = _databaseConnection.Loans.Find(id);
            ViewBag.AppUserId = new SelectList(_databaseConnection.AppUsers.Where(n => n.RoleId > 1).ToList(),
                "AppUserId",
                "Name", loan.AppUserId);
            ViewBag.BankId = new SelectList(_databaseConnection.Banks.ToList(), "BankId",
                "Name", loan.BankId);
            return View(loan);
        }

        [HttpPost]
        [SessionExpireFilter]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Loan loan)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            loan.LastModifiedBy = signedInUserId;
            loan.DateLastModified = DateTime.Now;

            var transaction = _databaseConnection.Transactions.Find(loan.TransactionId);
            var accountType = _databaseConnection.TransactionTypes.Find(loan.TransactionTypeId);
            if (accountType.Debit || accountType.Loan)
            {
                transaction.Action = TransactionAction.Debit.ToString();
            }

            if (accountType.Credit)
            {
                transaction.Action = TransactionAction.Credit.ToString();
            }

            _databaseConnection.Entry(transaction).State = EntityState.Modified;
            _databaseConnection.SaveChanges();

            _databaseConnection.Entry(loan).State = EntityState.Modified;
            _databaseConnection.SaveChanges();

            TempData["display"] = "You have successfully modified the loan!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public ActionResult Delete(long id)
        {
            try
            {
                var loan = _databaseConnection.Loans.Find(id);
                _databaseConnection.Loans.Remove(loan);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully deleted the loan!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CooperativeAccounting/Controllers/MinuteController.cs
using System;
using System.Linq;
using CooperativeAccounting.Models.DataBaseConnections;
using CooperativeAccounting.Models.Encryption;
using CooperativeAccounting.Models.Entities;
using CooperativeAccounting.Models.Enum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CooperativeAccounting.Controllers
{
    public class MinuteController : Controller
    {

        private readonly CooperativeAccountingDataContext _databaseConnection;

        /// <summary>
        ///     Intitialize some connections from the class constructor
        /// </summary>
        /// <param name="databaseConnection"></param>
        public MinuteController(CooperativeAccountingDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
        }
        [SessionExpireFilter]
        public IActionResult Index()
        {
            return View(_databaseConnection.Minutes.ToList());
        }
        [SessionExpireFilter]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [SessionExpireFilter]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Minute minute)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            minute.CreatedBy = signedInUserId;
            minute.LastModifiedBy = signedInUserId;
            minute.DateCreated = DateTime.Now;
            minute.DateLastModified = DateTime.Now;
            _databaseConnection.Minutes.Add(minute);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully added a new Minute!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public IActionResult Edit(long id)
        {
            var minute = _databaseConnection.Minutes.Find(id);
            return View(minute);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Edit(Minute minute)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            minute.LastModifiedBy = signedInUserId;
            minute.DateLastModified = DateTime.Now;
            _databaseConnection.Entry(minute).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully modified the Minute!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public ActionResult Delete(long id)
        {
            try
            {
                var minute = _databaseConnection.Minutes.Find(id);
                _databaseConnection.Minutes.Remove(minute);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully deleted the Minute!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CooperativeAccounting/Controllers/RoleController.cs
using System;
using System.Linq;
using CooperativeAccounting.Models.DataBaseConnections;
using CooperativeAccounting.Models.Encryption;
using CooperativeAccounting.Models.Entities;
using CooperativeAccounting.Models.Enum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CooperativeAccounting.Controllers
{
    public class RoleController : Controller
    {
        private readonly CooperativeAccountingDataContext _databaseConnection;

        /// <summary>
        ///     Intitialize some connections from the class constructor
        /// </summary>
        /// <param name="databaseConnection"></param>
        public RoleController(CooperativeAccountingDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
        }
        [SessionExpireFilter]
        public IActionResult Index()
        {
            return View(_databaseConnection.Roles.ToList());
        }
        [SessionExpireFilter]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Create(Role role)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            role.CreatedBy = signedInUserId;
            role.LastModifiedBy = signedInUserId;
            role.DateCreated = DateTime.Now;
            role.DateLastModified = DateTime.Now;
            _databaseConnection.Roles.Add(role);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully added a new role!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public IActionResult Edit(long id)
        {
            var role = _databaseConnection.Roles.Find(id);
            return View(role);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Edit(Role role)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            role.LastModifiedBy = signedInUserId;
            role.DateLastModified = DateTime.Now;
            _databaseConnection.Entry(role).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully modified the role!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public ActionResult Delete(long id)
        {
            try
            {
                var role = _databaseConnection.Roles.Find(id);
                _databaseConnection.Roles.Remove(role);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully deleted the role!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

    }
}

CooperativeAccounting/Controllers/WelfareController.cs
using System;
using System.Linq;
using CooperativeAccounting.Models.DataBaseConnections;
using CooperativeAccounting.Models.Encryption;
using CooperativeAccounting.Models.Entities;
using CooperativeAccounting.Models.Enum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CooperativeAccounting.Controllers
{
    public class WelfareController : Controller
    {

        private readonly CooperativeAccountingDataContext _databaseConnection;

        /// <summary>
        ///     Intitialize some connections from the class constructor
        /// </summary>
        /// <param name="databaseConnection"></param>
        public WelfareController(CooperativeAccountingDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
        }
        [SessionExpireFilter]
        public IActionResult Index()
        {
            return View(_databaseConnection.Welfares.Include(n=>n.AppUser).ToList());
        }
        [SessionExpireFilter]
        public IActionResult Create(string member)
        {
            var welfare = new Welfare();
            if (!String.IsNullOrEmpty(member) && member == "yes")
            {
                welfare.Member = true;
            }
            if (!String.IsNullOrEmpty(member) && member == "no")
            {
                welfare.Member = false;
            }

            ViewBag.AppUserId = new SelectList(_databaseConnection.AppUsers.Where(n=>n.RoleId > 1).ToList(), "AppUserId",
                "Name");
            return View(welfare);
        }
        [HttpPost]
        [SessionExpireFilter]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Welfare welfare)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            welfare.CreatedBy = signedInUserId;
            welfare.LastModifiedBy = signedInUserId;
            welfare.DateCreated = DateTime.Now;
            welfare.DateLastModified = DateTime.Now;
            _databaseConnection.Welfares.Add(welfare);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully added a new Welfare Request!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public IActionResult Edit(long id)
        {
            var welfare = _databaseConnection.Welfares.Find(id);
            ViewBag.AppUserId = new SelectList(_databaseConnection.AppUsers.Where(n => n.RoleId > 1).ToList(), "AppUserId",
                "Name",welfare.AppUserId);
            return View(welfare);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Edit(Welfare welfare)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            welfare.LastModifiedBy = signedInUserId;
            welfare.DateLastModified = DateTime.Now;
            _databaseConnection.Entry(welfare).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully modified the Welfare Request!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public ActionResult Delete(long id)
        {
            try
            {
                var welfare = _databaseConnection.Welfares.Find(id);
                _databaseConnection.Welfares.Remove(welfare);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully deleted the Welfare Request!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CooperativeAccounting/Views/Shared/LeftSideBar.cshtml
@using CooperativeAccounting.Models.Entities
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@{
    AppUser user = null;
    if (Context.Session.GetString("User") != null)
    {
        user = JsonConvert.DeserializeObject<AppUser>(Context.Session.GetString("User"));
    }
}
<!-- Left navbar-header -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse slimscrollsidebar">
        <ul class="nav" id="side-menu">
            @*<li class="user-pro">
                <a href="#" class="waves-effect">
                    <img src="~/images/avatar.png" alt="user-img" class="img-circle">
                    <span class="hide-menu">
                        @user?.Name<span class="fa arrow"></span>
                    </span>
                </a>
                @if (user != null)
                {
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="@Url.Action("Profile", "Account")"><i class="ti-user"></i> My Profile & Settings</a>
                        </li>
                        <li>
                            <a href="@Url.Action("LogOut", "Account")"><i class="fa fa-power-off"></i> Logout</a>
                        </li>
                    </ul>
                }

            </li>*@
            <li class="nav-small-cap m-t-10">--Main Menu</li>
            <li>
                <a href="@Url.Action("Dashboard", "Home")" class="waves-effect active">
                    <i class="linea-icon linea-basic fa-fw fa fa-dashboard"></i> <span class="hide-menu"> Dashboard</span>
                </a>
            </li>
            @if (user != null && user.Role.ManageMembers)
            {
                <li>
                    <a class="waves-effect">
                        <i class="linea-icon linea-basic fa-fw fa fa-users"></i> <span class="hide-menu">Members <span class="fa arrow"></span></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="@Url.Action("Create", "AppUser")">New Member</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "AppUser")">Members</a>
                        </li>
                    </ul>
                </li>
            }
            @if (user != null && user.Role.ManageMemberRoles)
            {
                <li>
                    <a class="waves-effect">
                        <i class="linea-icon linea-basic fa-fw fa fa-lock"></i> <span class="hide-menu">Role & Permissions <span class="fa arrow"></span></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="@Url.Action("Create", "Role")">Add Role</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Role")">Roles</a>
                        </li>
                    </ul>
                </li>
            }
            @if (user != null && user.Role.ManageAllTransaction)
            {
                <li>
                    <a class="waves-effect">
                        <i class="linea-icon linea-basic fa-fw fa fa-bank"></i> <span class="hide-menu"> General Transactions <span class="fa arrow"></span></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="@Url.Action("Create", "Transaction")">Add Transaction</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Transaction")">All Transactions(General Ledger)</a>
                        </li>
                        <li>
                            <a href="@Url.Action("BalanceSheet", "Transaction")">Balance Sheet</a>
                        </li>
                        <li>
                            <a href="@Url.Action("TrialBalance", "Transaction")">Trian Balance</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Years", "Transaction",new{page = "SalaryDeduction"})">Salary Deductions</a>
                        </li>
                    </ul>
                </li>
            }
            @if (user != null && user.Role.ManageCashTransaction)
            {
                <li>
                    <a class="waves-effect">
                        <i class="linea-icon linea-basic fa-fw fa fa-bank"></i> <span class="hide-menu"> Cash Transactions <span class="fa arrow"></span></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="@Url.Action("CashBook", "Transaction")">Cash Book</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Years", "Transaction",new{page = "CashContribution"})">Cash Contributions</a>
                        </li>
                        <li>
                            <a href="@Url.Action("PayCashContribution", "Transaction")">Pay Cash Contributions</a>
                        </li>
                    </ul>
                </li>
            }
            @if (user != null && user.Role.ManageLoan)
            {
                <li>
                    <a class="waves-effect">
                        <i class="linea-icon linea-basic fa-fw fa fa-bank"></i> <span class="hide-menu"> Loan Transactions <span class="fa arrow"></span></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="@Url.Action("Create", "Loan")">Apply Loan</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create", "Loan", new {id = "yes"})">Apply Emergency Loan</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Loan")">Loan Register</a>
                        </li>
                    </ul>
                </li>
            }
            @if (user != null && user.Role.ManageWelfare)
            {
                <li>
                    <a class="waves-effect">
                        <i class="linea-icon linea-basic fa-fw fa fa-book"></i> <span class="hide-menu">Welfare<span class="fa arrow"></span></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="@Url.Action("Create", "Welfare",new{member = "no"})">Add General Welfare</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Create", "Welfare",new{member = "yes"})">Add Member Welfare</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Welfare")">Welfares</a>
                        </li>
                    </ul>
                </li>
            }
            @if (user != null && user.Role.ManageMinute)
            {
                <li>
                    <a class="waves-effect">
                        <i class="linea-icon linea-basic fa-fw fa fa-book"></i> <span class="hide-menu">Meetings Minutes<span class="fa arrow"></span></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="@Url.Action("Create", "Minute")">Add Minute</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Minute")">Minutes</a>
                        </li>
                    </ul>
                </li>
            }
            @if (user != null && user.Role.ManageTransactionType)
            {
                <li>
                    <a class="waves-effect">
                        <i class="linea-icon linea-basic fa-fw fa fa-list"></i> <span class="hide-menu">Transaction Types <span class="fa arrow"></span></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="@Url.Action("Create", "TransactionType")">Add Transaction Type</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "TransactionType")">Transaction Types</a>
                        </li>
                    </ul>
                </li>
            }
        </ul>
    </div>
</div>
<!-- Left navbar-header end -->

CooperativeAccounting/Views/Shared/Navigation.cshtml
@using CooperativeAccounting.Models.Entities
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@{
    AppUser user = null;
    if (Context.Session.GetString("User") != null)
    {
        user = JsonConvert.DeserializeObject<AppUser>(Context.Session.GetString("User"));
    }
}
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse">
            <i class="ti-menu"></i>
        </a>
        <div class="top-left-part">
            <a class="logo" href="@Url.Action("Index", "Home")">
                <b>
                    <img src="~/Dashboard/plugins/images/eliteadmin-logo.png" alt="home"/>
                </b>
                <span class="hidden-xs">
                    <img src="~/Dashboard/plugins/images/eliteadmin-text.png" alt="home"/>
                </span>
            </a>
        </div>
        <ul class="nav navbar-top-links navbar-left hidden-xs">
            <li>
                <a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light">
                    <i class="icon-arrow-left-circle ti-menu"></i>
                </a>
            </li>

        </ul>
        <ul class="nav navbar-top-links navbar-right pull-right">
            @*<li class="dropdown">
                <a class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#">
                    <i class="icon-envelope"></i>
                    <div class="notify">
                        <span class="heartbit"></span><span class="point"></span>
                    </div>
                </a>
                <ul class="dropdown-menu mailbox animated bounceInDown">
                    <li>
                        <div class="drop-title">You have 4 new messages</div>
                    </li>
                    <li>
                        <div class="message-center">
                            <a href="#">
                                <div class="user-img">
                                    <img src="~/Dashboard/plugins/images/users/pawandeep.jpg" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span>
                                </div>
                                <div class="mail-contnet">
                                    <h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span>
                                </div>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="text-center" href="javascript:void(0);">
                            <strong>See all notifications</strong> <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                 /.dropdown-messages 
            </li>*@
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">
                    <img src="~/images/avatar.png" alt="user-img" width="36" class="img-circle"><b class="hidden-xs">@user?.Name</b>
                </a>
                <ul class="dropdown-menu dropdown-user animated flipInY">
                    <li>
                        <a href="@Url.Action("Edit", "AppUser",new{id = user.AppUserId})"><i class="ti-user"></i> My Profile</a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a href="@Url.Action("LogOut", "Account")"><i class="fa fa-power-off"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <!-- /.navbar-static-side -->
</nav>