CooperativeAccounting/Models/Entities/Welfare.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CooperativeAccounting.Models.Entities
{
    public class Welfare : Transport
    {
        public long WelfareId { get; set; }
        [Required]
        public string Reason { get; set; }
        [Required]
        public int Duration { get; set; }
        [DisplayName("Start Date")]
        [Required]
        public DateTime StartDate { get; set; }
        [DisplayName("Terminal Date")]
        [Required]
        public DateTime TerminalDate { get; set; }
        [Required]
        public double Amount { get; set; }
        [DisplayName("Welfare Owner")]
        public string Owner { get; set; }
        [DisplayName("Member")]
        public long? AppUserId { get; set; }
        [ForeignKey("AppUserId")]
        public AppUser AppUser { get; set; }
        public bool Member { get; set; }
    }
}

CooperativeAccounting/Controllers/TransactionTypeController.cs
using System;
using System.Linq;
using CooperativeAccounting.Models.DataBaseConnections;
using CooperativeAccounting.Models.Encryption;
using CooperativeAccounting.Models.Entities;
using CooperativeAccounting.Models.Enum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CooperativeAccounting.Controllers
{
    public class TransactionTypeController : Controller
    {

        private readonly CooperativeAccountingDataContext _databaseConnection;

        /// <summary>
        ///     Intitialize some connections from the class constructor
        /// </summary>
        /// <param name="databaseConnection"></param>
        public TransactionTypeController(CooperativeAccountingDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
        }
        [SessionExpireFilter]
        public IActionResult Index()
        {
            return View(_databaseConnection.TransactionTypes.ToList());
        }
        [SessionExpireFilter]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Create(TransactionType transactionType)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            transactionType.CreatedBy = signedInUserId;
            transactionType.LastModifiedBy = signedInUserId;
            transactionType.DateCreated = DateTime.Now;
            transactionType.DateLastModified = DateTime.Now;
            _databaseConnection.TransactionTypes.Add(transactionType);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully added a new Transaction Type!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public IActionResult Edit(long id)
        {
            var transactionType = _databaseConnection.TransactionTypes.Find(id);
            return View(transactionType);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Edit(TransactionType transactionType)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            transactionType.LastModifiedBy = signedInUserId;
            transactionType.DateLastModified = DateTime.Now;
            _databaseConnection.Entry(transactionType).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully modified the Transaction Type!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public ActionResult Delete(long id)
        {
            try
            {
                var transactionType = _databaseConnection.TransactionTypes.Find(id);
                _databaseConnection.TransactionTypes.Remove(transactionType);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully deleted the Account Type!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CooperativeAccounting/Controllers/WelfareController.cs
using System;
using System.Linq;
using CooperativeAccounting.Models.DataBaseConnections;
using CooperativeAccounting.Models.Encryption;
using CooperativeAccounting.Models.Entities;
using CooperativeAccounting.Models.Enum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CooperativeAccounting.Controllers
{
    public class WelfareController : Controller
    {

        private readonly CooperativeAccountingDataContext _databaseConnection;

        /// <summary>
        ///     Intitialize some connections from the class constructor
        /// </summary>
        /// <param name="databaseConnection"></param>
        public WelfareController(CooperativeAccountingDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
        }
        [SessionExpireFilter]
        public IActionResult Index()
        {
            return View(_databaseConnection.Welfares.Include(n=>n.AppUser).ToList());
        }
        [SessionExpireFilter]
        public IActionResult Create(string member)
        {
            var welfare = new Welfare();
            if (!String.IsNullOrEmpty(member) && member == "yes")
            {
                welfare.Member = true;
            }
            if (!String.IsNullOrEmpty(member) && member == "no")
            {
                welfare.Member = false;
            }

            ViewBag.AppUserId = new SelectList(_databaseConnection.AppUsers.Where(n=>n.RoleId > 1).ToList(), "AppUserId",
                "Name");
            return View(welfare);
        }
        [HttpPost]
        [SessionExpireFilter]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Welfare welfare)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            welfare.CreatedBy = signedInUserId;
            welfare.LastModifiedBy = signedInUserId;
            welfare.DateCreated = DateTime.Now;
            welfare.DateLastModified = DateTime.Now;
            _databaseConnection.Welfares.Add(welfare);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully added a new Welfare Request!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public IActionResult Edit(long id)
        {
            var welfare = _databaseConnection.Welfares.Find(id);
            ViewBag.AppUserId = new SelectList(_databaseConnection.AppUsers.Where(n => n.RoleId > 1).ToList(), "AppUserId",
                "Name",welfare.AppUserId);
            return View(welfare);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Edit(Welfare welfare)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            welfare.LastModifiedBy = signedInUserId;
            welfare.DateLastModified = DateTime.Now;
            _databaseConnection.Entry(welfare).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully modified the Welfare Request!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public ActionResult Delete(long id)
        {
            try
            {
                var welfare = _databaseConnection.Welfares.Find(id);
                _databaseConnection.Welfares.Remove(welfare);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully deleted the Welfare Request!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CooperativeAccounting/Views/Welfare/Create.cshtml
@model CooperativeAccounting.Models.Entities.Welfare
@{
    Layout = "_Layout";
}

@section Css
{
    <link rel="stylesheet" href="~/Dashboard/plugins/bower_components/html5-editor/bootstrap-wysihtml5.css"/>
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Manage Welfare(s)</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li>
                <a href="#">Welfares</a>
            </li>
            <li>
                <a href="#">Add Welfares</a>
            </li>
        </ol>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title m-b-0">Add Welfares</h3>
            <p class="text-muted m-b-30 font-13">Create Welfare</p>
            @using (Html.BeginForm("Create", "Welfare", FormMethod.Post, new {enctype = "multipart/form-data", role = "form"}))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                if (Model.Member)
                 {
                     <div class="form-group row">
                         @Html.LabelFor(model => model.AppUserId, new {@class = "col-2 col-form-label"})
                         <div class="col-10">
                             @Html.DropDownListFor(model => model.AppUserId,null,"Select Member", new {@class = "form-control", placeholder = "Please enter the Minute Title"})
                             @Html.ValidationMessageFor(model => model.AppUserId, "", new {@class = "text-danger"})
                         </div>
                     </div>
                }
                else
                {
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Owner, new {@class = "col-2 col-form-label"})
                        <div class="col-10">
                            @Html.EditorFor(model => model.Owner, new {htmlAttributes = new {@class = "form-control", placeholder = "Please enter the Welfare Owners Name"}})
                            @Html.ValidationMessageFor(model => model.Owner, "", new {@class = "text-danger"})
                        </div>
                    </div>
                }

          
                <div class="form-group row">
                    @Html.LabelFor(model => model.Reason, new {@class = "col-2 col-form-label"})
                    <div class="col-10">
                        @Html.TextAreaFor(model => model.Reason, new {@class = "form-control", placeholder = "Please enter the Minute", id = "mymce"})
                        @Html.ValidationMessageFor(model => model.Reason, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Amount, new {@class = "col-2 col-form-label"})
                    <div class="col-10">
                        @Html.EditorFor(model => model.Amount, new {htmlAttributes = new {@class = "form-control", placeholder = "Please enter the Welfare Amount"}})
                        @Html.ValidationMessageFor(model => model.Amount, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.StartDate, new {@class = "col-2 col-form-label"})
                    <div class="col-10">
                        @*<input type="text" name="Date" class="form-control mydatepicker" placeholder="mm/dd/yyyy">*@
                        @Html.TextBoxFor(model => model.StartDate, new {@class = "form-control mydatepicker", placeholder = "Please select the Start Date"})
                        @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
                    </div>

                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Duration, new {@class = "col-2 col-form-label"})
                    <div class="col-10">
                        @Html.EditorFor(model => model.Duration, new {htmlAttributes = new {@class = "form-control", placeholder = "Please enter the Welfare Duration"}})
                        @Html.ValidationMessageFor(model => model.Duration, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.TerminalDate, new {@class = "col-2 col-form-label"})
                    <div class="col-10">
                        @*<input type="text" name="Date" class="form-control mydatepicker" placeholder="mm/dd/yyyy">*@
                        @Html.TextBoxFor(model => model.TerminalDate, new {@class = "form-control mydatepicker", placeholder = "Please select the Terminal Date"})
                        @Html.ValidationMessageFor(model => model.TerminalDate, "", new {@class = "text-danger"})
                    </div>

                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="@Url.Action("Index", "TransactionType")" class="btn btn-default">Cancel</a>
                </div>
            }
        </div>
    </div>
</div>

@section Functions
{
    <script src="~/Dashboard/plugins/bower_components/tinymce/tinymce.min.js"></script>
    <script>
        $(document).ready(function() {
            if ($("#mymce").length > 0) {
                tinymce.init({
                    selector: "textarea#mymce",
                    theme: "modern",
                    height: 300,
                    plugins: [
                        "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                        "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                        "save table contextmenu directionality emoticons template paste textcolor"
                    ],
                    toolbar:
                        "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons",
                });
            }
        });
    </script>
    <!--Style Switcher -->
    <script src="../plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>
}

CooperativeAccounting/Views/Welfare/Edit.cshtml
@model CooperativeAccounting.Models.Entities.Welfare
@{
    Layout = "_Layout";
}

@section Css
    {
    <link rel="stylesheet" href="~/Dashboard/plugins/bower_components/html5-editor/bootstrap-wysihtml5.css" />
}

<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Manage Welfare(s)</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li>
                <a href="#">Welfares</a>
            </li>
            <li>
                <a href="#">Add Welfares</a>
            </li>
        </ol>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title m-b-0">Edit Welfares</h3>
            <p class="text-muted m-b-30 font-13">Edit Welfare</p>
            @using (Html.BeginForm("Edit", "Welfare", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.WelfareId)
                @Html.HiddenFor(m => m.DateCreated)
                @Html.HiddenFor(m => m.CreatedBy)
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                if (Model.Member)
                {
                    <div class="form-group row">
                        @Html.LabelFor(model => model.AppUserId, new { @class = "col-2 col-form-label" })
                        <div class="col-10">
                            @Html.DropDownListFor(model => model.AppUserId, null, "Select Member", new { htmlAttributes = new { @class = "form-control", placeholder = "Please enter the Minute Title" } })
                            @Html.ValidationMessageFor(model => model.AppUserId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                }
                else
                {
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Owner, new { @class = "col-2 col-form-label" })
                        <div class="col-10">
                            @Html.EditorFor(model => model.Owner, new { htmlAttributes = new { @class = "form-control", placeholder = "Please enter the Welfare Owners Name" } })
                            @Html.ValidationMessageFor(model => model.Owner, "", new { @class = "text-danger" })
                        </div>
                    </div>
                }


                <div class="form-group row">
                    @Html.LabelFor(model => model.Reason, new { @class = "col-2 col-form-label" })
                    <div class="col-10">
                        @Html.TextAreaFor(model => model.Reason, new { @class = "form-control", placeholder = "Please enter the Minute", id = "mymce" })
                        @Html.ValidationMessageFor(model => model.Reason, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Amount, new { @class = "col-2 col-form-label" })
                    <div class="col-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", placeholder = "Please enter the Welfare Amount" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.StartDate, new { @class = "col-2 col-form-label" })
                    <div class="col-10">
                        @*<input type="text" name="Date" class="form-control mydatepicker" placeholder="mm/dd/yyyy">*@
                        @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control mydatepicker", placeholder = "Please select the Start Date" })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Duration, new { @class = "col-2 col-form-label" })
                    <div class="col-10">
                        @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", placeholder = "Please enter the Welfare Duration" } })
                        @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.TerminalDate, new { @class = "col-2 col-form-label" })
                    <div class="col-10">
                        @*<input type="text" name="Date" class="form-control mydatepicker" placeholder="mm/dd/yyyy">*@
                        @Html.TextBoxFor(model => model.TerminalDate, new { @class = "form-control mydatepicker", placeholder = "Please select the Terminal Date" })
                        @Html.ValidationMessageFor(model => model.TerminalDate, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="@Url.Action("Index", "TransactionType")" class="btn btn-default">Cancel</a>
                </div>
            }
        </div>
    </div>
</div>

@section Functions
    {
    <script src="~/Dashboard/plugins/bower_components/tinymce/tinymce.min.js"></script>
    <script>
        $(document).ready(function() {
            if ($("#mymce").length > 0) {
                tinymce.init({
                    selector: "textarea#mymce",
                    theme: "modern",
                    height: 300,
                    plugins: [
                        "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                        "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                        "save table contextmenu directionality emoticons template paste textcolor"
                    ],
                    toolbar:
                        "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons",
                });
            }
        });
    </script>
    <!--Style Switcher -->
    <script src="../plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>
}

CooperativeAccounting/Views/Welfare/Index.cshtml
@model List<CooperativeAccounting.Models.Entities.Welfare>
@{
    Layout = "_Layout";
}

@section Css{
    <link href="~/Dashboard/plugins/bower_components/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
    <link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css"/>
    <!-- Custom CSS -->
    <link href="~/Dashboard/css/style.css" rel="stylesheet">
    <!-- color CSS -->
    <link href="~/Dashboard/css/colors/blue.css" id="theme" rel="stylesheet">
}

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel1">Delete Welfare</h4>
            </div>
            @using (Html.BeginForm("Delete", "Welfare"))
            {
                <input type="hidden" id="id" name="id"/>
                <div class="modal-body">

                    @Html.AntiForgeryToken()
                    <p>
                        Are you sure you want to delete the Welfare?
                    </p>

                </div>
                <div class="modal-footer">
                    <input type="submit" value="Delete" class="btn btn-danger pull-right fa fa-trash"/>
                    <input type="button" data-dismiss="modal" value="Cancel" class="btn btn-default pull-left"/>
                </div>
            }
        </div>
    </div>
</div>


<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Manage Welfare(s)</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li>
                <a href="#">Welfares</a>
            </li>
        </ol>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-md-6">
        <div class="btn-group">
            <a href="@Url.Action("Create", "Welfare")" class="btn btn-primary" data-toggle="tooltip" title="Add New Transaction Type">
                Add New
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
</div>
<br/>
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title m-b-0">List of all Minutes</h3>
            <p class="text-muted m-b-30">Export data to Copy, CSV, Excel, PDF & Print</p>
            <div class="table-responsive">
                <table id="example23" class="display nowrap" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Owner</th>
                        <th>Start Date</th>
                        <th>Duration</th>
                        <th>Terminal Date</th>
                        <th>Amount</th>
                        <th>Total</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td></td>
                                <td>@item.AppUser.Name</td>
                                <td>@item.StartDate</td>
                                <td>@item.Duration</td>
                                <td>@item.TerminalDate</td>
                                <td>@item.Amount</td>
                                <td>@(item.Amount * item.Duration)</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                                            Actions
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu pull-right" role="menu">
                                            <li>
                                                <a href="@Url.Action("Edit", "Welfare", new {id = item.WelfareId})" data-toggle="tooltip" title="View Deatils & Edit the Minute">
                                                    <i class="icon-docs"></i>View Details & Edit Welfare
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" data-toggle="tooltip" title="Delete the Minute" data-id="@item.WelfareId" data-toggle="modal" class="loadModal3">
                                                    <i class="icon-tag"></i>Delete Welfare
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Dashboard/plugins/bower_components/datatables/jquery.dataTables.min.js"></script>
    <!-- start - This is for export functionality only -->
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
}

@section Functions {
    <script>
        $(document).ready(function() {
            $(".loadModal3").click(function() { // Click to only happen on announce links
                $("#id").val($(this).data('id'));
                $('#myModal1').modal('show');
            });
        });
    </script>
    <script>
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    </script>
}