CooperativeAccounting/Controllers/AppUserController.cs
using System;
using System.IO;
using System.Linq;
using CooperativeAccounting.Models.DataBaseConnections;
using CooperativeAccounting.Models.Encryption;
using CooperativeAccounting.Models.Entities;
using CooperativeAccounting.Models.Enum;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CooperativeAccounting.Controllers
{
    public class AppUserController : Controller
    {
        private readonly CooperativeAccountingDataContext _databaseConnection;
        private readonly IHostingEnvironment _hostingEnv;

        /// <summary>
        ///     Intitialize some connections from the class constructor
        /// </summary>
        /// <param name="databaseConnection"></param>
        public AppUserController(IHostingEnvironment env, CooperativeAccountingDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
            _hostingEnv = env;
        }
        [SessionExpireFilter]
        public IActionResult Index()
        {
            ViewBag.Transactions = _databaseConnection.Transactions.Include(n=>n.TransactionType).ToList();
            return View(_databaseConnection.AppUsers.ToList());
        }
        /// <summary>
        ///     Sends Json responds object to view with lga of the state requested via an Ajax call
        /// </summary>
        /// <param name="id"> state id</param>
        /// <returns>lgas</returns>
        /// Microsoft.CodeDom.Providers.DotNetCompilerPlatform
        public JsonResult GetLgaForState(int id)
        {
            var lgas = _databaseConnection.Lgas.Where(n => n.StateId == id-1);
            return Json(lgas);
        }
        [SessionExpireFilter]
        public IActionResult Create()
        {
            ViewBag.State = new SelectList(_databaseConnection.States, "StateId", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Create(AppUser appUser,IFormFile Logo)
        {

            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            appUser.CreatedBy = signedInUserId;
            appUser.LastModifiedBy = signedInUserId;
            appUser.DateCreated = DateTime.Now;
            appUser.DateLastModified = DateTime.Now;
            appUser.RoleId = 2;

            //generate password
            var generator = new Random();
            var number = generator.Next(0, 1000000).ToString("D6");

            appUser.Password = new Hashing().HashPassword(number);
            appUser.ConfirmPassword = appUser.Password;

            if (_databaseConnection.AppUsers.Where(n => n.Email == appUser.Email).ToList().Count > 0)
            {
                TempData["display"] = "A member with the same email already exist!";

                TempData["notificationtype"] = NotificationType.Error.ToString();
                return View(appUser);
            }
            //upload user logo if any file is uploaded
            if (Logo != null && !String.IsNullOrEmpty(Logo.FileName))
            {
                var fileInfo = new FileInfo(Logo.FileName);
                var ext = fileInfo.Extension.ToLower();
                var name = DateTime.Now.ToFileTime().ToString();
                var fileName = name + ext;
                var uploadedImage = _hostingEnv.WebRootPath + $@"\UploadedFiles\ProfilePicture\{fileName}";

                using (var fs = System.IO.File.Create(uploadedImage))
                {
                    if (fs != null)
                    {
                        Logo.CopyTo(fs);
                        fs.Flush();
                        appUser.ProfilePicture = fileName;
                    }
                }
            }
            _databaseConnection.AppUsers.Add(appUser);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully added a new member!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public IActionResult Edit(long id)
        {
            var appUser = _databaseConnection.AppUsers.Find(id);
            ViewBag.State = new SelectList(_databaseConnection.States, "StateId", "Name",appUser.StateId);
            return View(appUser);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Edit(AppUser appUser, IFormFile Logo)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            appUser.LastModifiedBy = signedInUserId;
            appUser.DateLastModified = DateTime.Now;
            //upload user logo if any file is uploaded
            if (Logo != null && !String.IsNullOrEmpty(Logo.FileName))
            {
                var fileInfo = new FileInfo(Logo.FileName);
                var ext = fileInfo.Extension.ToLower();
                var name = DateTime.Now.ToFileTime().ToString();
                var fileName = name + ext;
                var uploadedImage = _hostingEnv.WebRootPath + $@"\UploadedFiles\ProfilePicture\{fileName}";

                using (var fs = System.IO.File.Create(uploadedImage))
                {
                    if (fs != null)
                    {
                        Logo.CopyTo(fs);
                        fs.Flush();
                        appUser.ProfilePicture = fileName;
                    }
                }
            }

            _databaseConnection.Entry(appUser).State = EntityState.Modified;
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully modified the member!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public ActionResult Delete(long id)
        {
            try
            {
                var appUser = _databaseConnection.AppUsers.Find(id);
                _databaseConnection.AppUsers.Remove(appUser);
                _databaseConnection.SaveChanges();
                TempData["display"] = "You have successfully deleted the member!";
                TempData["notificationtype"] = NotificationType.Success.ToString();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CooperativeAccounting/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using CooperativeAccounting.Models.DataBaseConnections;
using CooperativeAccounting.Models.Encryption;
using CooperativeAccounting.Models.Entities;
using CooperativeAccounting.Models.Enum;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace CooperativeAccounting.Controllers
{
    public class TransactionController : Controller
    {
        private readonly CooperativeAccountingDataContext _databaseConnection;

        /// <summary>
        ///     Intitialize some connections from the class constructor
        /// </summary>
        /// <param name="databaseConnection"></param>
        public TransactionController(CooperativeAccountingDataContext databaseConnection)
        {
            _databaseConnection = databaseConnection;
        }
        [SessionExpireFilter]
        public IActionResult Index()
        {
            return View(_databaseConnection.Transactions.Include(n => n.AppUser).Include(n => n.TransactionType).ToList());
        }
        [SessionExpireFilter]
        public IActionResult Years(string page)
        {
            ViewBag.Page = page;
            return View();
        }
        [SessionExpireFilter]
        public IActionResult Months(int? id, string page)
        {
            ViewBag.Year = id;
            ViewBag.Page = page;
            return View();
        }
        [SessionExpireFilter]
        public IActionResult SalaryDeduction(int year, int month)
        {
            ViewBag.Year = year;
            ViewBag.Month = month;
            ViewBag.Loans= _databaseConnection.Loans.Include(n => n.AppUser).ToList();
            ViewBag.Welfares = _databaseConnection.Welfares.Include(n => n.AppUser).ToList();
            return View(_databaseConnection.AppUsers.ToList());
        }
        [SessionExpireFilter]
        public IActionResult CashContribution(int year,int month)
        {
            ViewBag.Year = year;
            ViewBag.Month = month;
            return View(_databaseConnection.Transactions.Include(n => n.AppUser).Include(n => n.TransactionType)
                .ToList().Where(n => n.TransactionType.Cash).ToList().Where(n=>n.DateCreated.Year == year && n.DateCreated.Month == month).ToList());
        }
        public IActionResult PayCashContribution(int year, int month)
        {
            ViewBag.Year = year;
            ViewBag.Month = month;
            return View(_databaseConnection.AppUsers.ToList());
        }

        /// <summary>
        ///     Search for photographer
        /// </summary>
        /// <param name="table_records"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PayCashContribution(int[] table_records)
        {
            try
            {
                List<Transaction>usersTransactions = new List<Transaction>();
                if (table_records != null && table_records.Length > 0)
                {
                    var length = table_records.Length;
                    for (var i = 0; i < length; i++)
                    {
                        long userId = Convert.ToInt64(table_records[i]);
                        var user = _databaseConnection.AppUsers.Find(userId);
                        var transaction = new Transaction
                        {
                            DateCreated = DateTime.Now,
                            TransactionDate = DateTime.Now,
                            TransactionName = "Monthly Contribution",
                            CreatedBy = userId,
                            LastModifiedBy = userId,
                            AppUserId = userId,
                            Action = TransactionAction.Credit.ToString(),
                            Amount = user.MonthlyContribution,
                            TransactionTypeId = 1,
                            BankId = 1,
                            DateLastModified = DateTime.Now,
                            VoucherNumber = "NIL"
                        };

                        usersTransactions.Add(transaction);

                    }
                    _databaseConnection.Transactions.AddRange(usersTransactions);
                    _databaseConnection.SaveChanges();
                    TempData["display"] = "You have successfully paid the member(s) monthly contribution!";
                    TempData["notificationtype"] = NotificationType.Success.ToString();
                    return RedirectToAction("PayCashContribution");
                }

                TempData["display"] = "You did not select any member!";
                TempData["notificationtype"] = NotificationType.Error.ToString();
                return RedirectToAction("PayCashContribution");


            }
            catch (Exception ex)
            {
                TempData["display"] = ex.ToString();
                TempData["notificationtype"] = NotificationType.Error.ToString();
                return RedirectToAction("PayCashContribution");
            }
        }

        [SessionExpireFilter]
        public IActionResult PersonalLedger(long id)
        {
            return View(_databaseConnection.Transactions.Include(n => n.AppUser).Include(n => n.TransactionType).Where(n=>n.AppUserId == id).ToList());
        }
        [SessionExpireFilter]
        public IActionResult CashBook()
        {
            return View(_databaseConnection.Transactions.Include(n => n.AppUser).Include(n=>n.TransactionType)
                .ToList().Where(n=>n.TransactionType.Cash).ToList());
        }
        [SessionExpireFilter]
        public IActionResult TrialBalance()
        {
            return View(_databaseConnection.Transactions.Include(n => n.AppUser).Include(n => n.TransactionType)
                .ToList().Where(n => n.TransactionType.Cash).ToList());
        }
        [SessionExpireFilter]
        public IActionResult BalanceSheet()
        {
            return View(_databaseConnection.Transactions.Include(n => n.AppUser).Include(n => n.TransactionType)
                .ToList().Where(n => n.TransactionType.Asset || n.TransactionType.Equity || n.TransactionType.Liability).ToList());
        }
        [SessionExpireFilter]
        public IActionResult Create()
        {
            ViewBag.BankId = new SelectList(_databaseConnection.Banks.ToList(), "BankId",
                "Name");
            ViewBag.AppUserId = new SelectList(_databaseConnection.AppUsers.Where(n=>n.RoleId > 1).ToList(), "AppUserId",
                "Name");
            ViewBag.TransactionTypeId = new SelectList(_databaseConnection.TransactionTypes.Where(n=>n.TransactionTypeId != 2).ToList(), "TransactionTypeId",
                "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Create(Transaction transaction)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            transaction.CreatedBy = signedInUserId;
            transaction.LastModifiedBy = signedInUserId;
            transaction.DateCreated = DateTime.Now;
            transaction.DateLastModified = DateTime.Now;

            var accountType = _databaseConnection.TransactionTypes.Find(transaction.TransactionTypeId);
            if (accountType.Cash)
            {
                //generate Voucher Number
                var generator = new Random();
                var number = generator.Next(0, 1000000).ToString("D8");

                transaction.VoucherNumber = "CRP-" + number;
            }

            if (accountType.Debit)
            {
                transaction.Action = TransactionAction.Debit.ToString();
            }
            if (accountType.Credit)
            {
                transaction.Action = TransactionAction.Credit.ToString();
            }
            _databaseConnection.Transactions.Add(transaction);
            _databaseConnection.SaveChanges();
            TempData["display"] = "You have successfully added a new transaction!";
            TempData["notificationtype"] = NotificationType.Success.ToString();
            return RedirectToAction("Index");
        }
        [SessionExpireFilter]
        public IActionResult Edit(long id)
        {
            var transaction = _databaseConnection.Transactions.Find(id);
            ViewBag.AppUserId = new SelectList(_databaseConnection.AppUsers.Where(n => n.RoleId > 1).ToList(), "AppUserId",
                "Name",transaction.AppUserId);
            ViewBag.TransactionTypeId = new SelectList(_databaseConnection.TransactionTypes.Where(n => n.TransactionTypeId != 2).ToList(), "TransactionTypeId",
                "Name",transaction.TransactionTypeId);
            ViewBag.BankId = new SelectList(_databaseConnection.Banks.ToList(), "BankId",
                "Name",transaction.BankId);
            return View(transaction);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public IActionResult Edit(Transaction transaction)
        {
            var signedInUserId = HttpContext.Session.GetInt32("LoggedInUser");
            transaction.LastModifiedBy = signedInUserId;
            transaction.DateLastModified = DateTime.Now;

            var accountType = _databaseConnection.TransactionTypes.Find(transaction.TransactionTypeId);
            if (accountType.Debit)
            {
                transaction.Action = TransactionAction.Debit.ToString();
            }
            if (accountType.Credit)
            {
                transaction.Action = TransactionAction.Credit.ToString();
            }
            _databaseConnection.Entry(transaction).State = EntityState.Modified;
            _databaseConnection.SaveChanges();

CooperativeAccounting/Views/AppUser/Index.cshtml
@using CooperativeAccounting.Models.Entities
@model List<CooperativeAccounting.Models.Entities.AppUser>
@{
    Layout = "_Layout";
    List<Transaction> transactions = ViewBag.Transactions;
}

@section Css{
    <link href="~/Dashboard/plugins/bower_components/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
    <link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css"/>
    <!-- Custom CSS -->
    <link href="~/Dashboard/css/style.css" rel="stylesheet">
    <!-- color CSS -->
    <link href="~/Dashboard/css/colors/blue.css" id="theme" rel="stylesheet">
}

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel1">Delete Member</h4>
            </div>
            @using (Html.BeginForm("Delete", "AppUser"))
            {
                <input type="hidden" id="id" name="id"/>
                <div class="modal-body">

                    @Html.AntiForgeryToken()
                    <p>
                        Are you sure you want to delete the Member?
                    </p>

                </div>
                <div class="modal-footer">
                    <input type="submit" value="Delete" class="btn btn-danger pull-right fa fa-trash"/>
                    <input type="button" data-dismiss="modal" value="Cancel" class="btn btn-default pull-left"/>
                </div>
            }
        </div>
    </div>
</div>


<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Manage Member(s)</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li>
                <a href="#">Members</a>
            </li>
        </ol>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-md-6">
        <div class="btn-group">
            <a href="@Url.Action("Create", "AppUser")" class="btn btn-primary" data-toggle="tooltip" title="Add Member">
                Add New
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
</div>
<br/>
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title m-b-0">List of all Members</h3>
            <p class="text-muted m-b-30">Export data to Copy, CSV, Excel, PDF & Print</p>
            <div class="table-responsive">
                <table id="example23" class="display nowrap" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Date Joined</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                        @*<th>Available Balance</th>*@
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model.Where(n=>n.RoleId > 1).ToList())
                        {
                            <tr>
                                <td></td>
                                <td>@item.DateCreated.ToString("D")</td>
                                <td>@item.Name</td>
                                <td>@item.Email</td>
                                <td>@item.Mobile</td>
                                @*<td>
                                     @if (transactions != null)
                                     {
                                         @(transactions.Where(n => n.AppUserId == item.AppUserId && n.TransactionType.Credit).Sum(n => n.Amount) - transactions.Where(n => n.AppUserId == item.AppUserId && n.TransactionType.Debit).Sum(n => n.Amount))
                                     }
                                 </td>*@
                                <td class="text-center">
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                                            Actions
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu pull-right" role="menu">
                                            <li>
                                                <a href="@Url.Action("Edit", "AppUser", new {id = item.AppUserId})" data-toggle="tooltip" title="View Deatils & Edit the Account Type">
                                                    <i class="icon-docs"></i>View Details & Edit Member
                                                </a>
                                            </li>
                                            <li>
                                                <a href="@Url.Action("PersonalLedger", "Transaction", new {id = item.AppUserId})" data-toggle="tooltip" title="View Personal Ledger">
                                                    <i class="icon-docs"></i>View Personal Ledger
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" data-toggle="tooltip" title="Delete the Account Type" data-id="@item.AppUserId" data-toggle="modal" class="loadModal3">
                                                    <i class="icon-tag"></i>Delete Member
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/Dashboard/plugins/bower_components/datatables/jquery.dataTables.min.js"></script>
    <!-- start - This is for export functionality only -->
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
}

@section Functions {
    <script>
        $(document).ready(function() {
            $(".loadModal3").click(function() { // Click to only happen on announce links
                $("#id").val($(this).data('id'));
                $('#myModal1').modal('show');
            });
        });
    </script>
    <script>
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    </script>
}